# Generated by Django 2.0.7 on 2018-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='turn',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
