# Generated by Django 2.0.7 on 2018-09-06 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180906_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(default=uuid.UUID('82cf7b25-f5ee-47f0-9251-5272c3f490d0'), max_length=30, unique=True),
        ),
    ]
