# Generated by Django 2.0.7 on 2018-09-06 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180906_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(default=uuid.UUID('d444848e-a5c9-4230-9780-392f8f22aa23'), max_length=30, unique=True),
        ),
    ]
