# Generated by Django 2.0.7 on 2018-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180906_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
