# Generated by Django 2.0.7 on 2018-09-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180906_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='created_datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='created_datetime',
            new_name='created_at',
        ),
    ]
